### ISSUE TITLE
Сгенерировать пустой проект

### ISSUE THREAD

**Issue by grihabor** [zveronics/zveronics-android-client#1]

**Comment by RedSnail** [comment]
Всм новый репозиторий? Если да, то чтобы он был private надо чтобы его сделал ты

**Comment by grihabor** [comment]
Не понял, о чем ты. Чтобы сделать private репозиторий, надо перелезать на гитлаб. Доступ к этой репе всем дал

**Comment by RedSnail** [comment]
А, то есть у нас все публично?

**Comment by grihabor** [comment]
Ну на гитхабе бесплатные только публичные проекты

**Comment by artem-glubshev** [comment]
Вроде готово, @grihabor, чекай
